import Header from "@/components/Header/Header"
import './index.css'
import { Metadata } from "next"
import StoreContextProvider from '../context/StoreContext'
import Footer  from "../components/Footer/Footer"
export const metadata: Metadata = {
  title: {
    default: "Next.js",
    template:"%s | Just For Fun",
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="main-content">
        <Header/>
        <StoreContextProvider>
          {children}
        </StoreContextProvider>
        </div>
      <Footer/>
      </body>
    </html>
  )
}
